name: Build and Push Docker Image

on:
  push:
    branches:
      - docker/trial_image
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
        default: 'trial'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set Tag variable
        run: |
          GIT_TAG=${GITHUB_REF#refs/tags/}
          if [ -n "${{ inputs.image_tag }}" ]; then
            DOCKER_TAG=${{ inputs.image_tag }}
          else
            DOCKER_TAG=trial
          fi
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Log in to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push multi-arch image Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            771592594/power-scheduler-console:${{ env.DOCKER_TAG }}
            ghcr.io/${{ github.actor }}/power-scheduler-console:${{ env.DOCKER_TAG }}
            registry.cn-hangzhou.aliyuncs.com/wcz-docker-repo/power-scheduler-console:${{ env.DOCKER_TAG }}
